# Generated by Django 4.1.7 on 2023-02-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appminimarket', '0002_alter_boleta_id_boleta_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='direccion_boleta',
            new_name='nombrecliente_boleta',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='total_boleta',
            new_name='total_ventas',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='dni_boleta',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='ruc_boleta',
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='preciounitario_detalleboleta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='subtotal_detalleboleta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
