# Generated by Django 4.1.7 on 2023-02-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('ruc_boleta', models.IntegerField(null=True)),
                ('direccion_boleta', models.CharField(max_length=60, null=True)),
                ('dni_boleta', models.IntegerField(null=True)),
                ('fecha_boleta', models.DateField(null=True)),
                ('total_boleta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=40, null=True)),
                ('imagen_categoria', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30, null=True)),
                ('apellidos_usuarios', models.CharField(max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(max_length=30, null=True)),
                ('nombre_producto', models.CharField(max_length=25, null=True)),
                ('descripcion_producto', models.CharField(max_length=50, null=True)),
                ('cant_stock_producto', models.IntegerField(null=True)),
                ('imagen_producto', models.CharField(max_length=100, null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appminimarket.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalleboleta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_detalleboleta', models.IntegerField(null=True)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appminimarket.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appminimarket.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appminimarket.usuario'),
        ),
    ]
